### ISSUE TITLE
Research approach for reading `README.md` for the preview page

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#1032] opened 2023-05-05 18:07 UTC
https://github.com/chanzuckerberg/napari-hub/issues/1023

**Comment by klai95** [comment] 2023-05-16 23:34
Prod:
https://www.napari-hub.org/plugins/test-detect-spots

Preview:
https://preview.napari-hub.org/klai95/test-detect-spots/1

**Comment by klai95** [comment] 2023-05-17 00:22
As discussed with @kandarpksk , the core dev feedback is that plugin developers don’t want a warning if the hub-specific DESCRIPTION.md is missing but there is a README.md

**Comment by richaagarwal** [comment] 2023-05-26 21:06
@klai95 and for posterity: 

The reason for the discrepancy in the above links for `test-detect-spots` is that there is no source code URL specified in https://pypi.org/pypi/test-detect-spots/json under `project_urls`, so that is expected behavior.  See https://github.com/chanzuckerberg/napari-hub/wiki/Customizing-your-plugin's-listing#source-code - this is the field we use to populate `code_repository`, and would need it to populate any descriptions that are specified in the plugin's github repository.

I believe the purpose of #1023 specifically is to use the README.md in the root level of the repository in the preview page, as we currently already do on the site.  For instance, https://preview.napari-hub.org/GenevieveBuckley/napari-meshio/2 should display the README populated at the root level of the repository and not have a warning. 

Thanks for your research!  I'm going to close this out now and I'll take over the work in #1023.

**Closed by richaagarwal** 2023-05-26 21:06 UTC
Labels: backend, spike
