### ISSUE TITLE
New napari-plugin does not show up on the napari-hub

### ISSUE THREAD

**Issue by haesleinhuepf** [chanzuckerberg/napari-hub#611] opened 2022-07-19 09:40 UTC
#### Description
Hi all,

a new plugin [napari-lattice](https://pypi.org/project/napari-lattice/) does not show up on the napari-hub, even though the [setup.cfg](https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/blob/master/setup.cfg#L15) appears correct to us.

Can you give us guidance on how to publish this plugin on the hub?

Thanks!

CC @pr4deepr

See also
* https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/issues/1https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/issues/1

**Comment by haesleinhuepf** [comment] 2022-07-21 21:07
Similar issue with this plugin :
https://pypi.org/project/napari-LF/

Cc @gschlafly

**Comment by richaagarwal** [comment] 2022-07-22 17:54
@haesleinhuepf Thanks for opening this! There might have been a lag between when the plugin was released and when we retrieve new plugin data (though this should be happening every 5 minutes). Looks like those are showing up now.

Do you remember how much time had passed since release, at the time you weren't seeing the data on napari-hub?

**Comment by gschlafly** [comment] 2022-07-22 18:03
@richaagarwal Our napari-LF plugin did not show up on napari-hub for at least four hours. When I checked 19 hours after the release, it was on napari-hub.

**Comment by richaagarwal** [comment] 2022-07-23 00:53
Thank you for the info, @gschlafly! 

It looks like there's a related issue https://github.com/chanzuckerberg/napari-hub/issues/200 so I think it's worth more investigation at this point.  I'll chat with the team to see when we might be able to prioritize this investigation.

**Comment by neuromusic** [comment] 2022-07-25 22:19
here's another example: https://github.com/napari/napari/issues/4862

`napari-deepfinder`

- released today on PyPI: https://pypi.org/project/napari-deepfinder/
- not found on the napari hub: https://www.napari-hub.org/plugins/napari-deepfinder

given that napari now uses the napari hub's API to get the list of available plugins, this is a problem that propagates to napari as well

**Comment by neuromusic** [comment] 2022-07-25 22:33
oddly, for `napari-deepfinder`, the API is returning a partial response with npe2-related fields only (h/t @tlambert03):

https://api.napari-hub.org/plugins/napari-deepfinder

``` json
{
  "conda": [],
  "display_name": "",
  "plugin_types": [],
  "reader_file_extensions": [],
  "writer_file_extensions": [],
  "writer_save_layers": []
}
```

otoh, the expected response for a non-existant plugin should be an empty blob:

https://api.napari-hub.org/plugins/foobar

``` json
{}
```

**Comment by DragaDoncila** [comment] 2022-07-25 23:59
Hmmm I thought the `npe2` API was entirely switched off still? We shouldn't be seeing these fields at all, no? Did we only switch off the frontend @codemonkey800 ?

**Comment by DragaDoncila** [comment] 2022-07-26 02:02
iirc the backend changes were just switching off the lambdas, I don't think we ever reverted the API changes. We should definitely gate it if we don't want to revert - not sure what the timelines are looking like for updating the backend work @richaagarwal

**Comment by richaagarwal** [comment] 2022-07-26 02:14
@DragaDoncila That's correct, we never reverted the API changes.  I don't know if there is a strong need to do this as we had discussed that no one else is really consuming the npe2 data yet, but maybe @neuromusic can weigh in here.  But if needed, then I am in support of reverting all npe2-enabled features changes.

**Comment by DragaDoncila** [comment] 2022-07-26 02:30
Do you think it's preferable to revert rather than just add a "gate" to hold the fields back? I think a lot of the API stuff won't change so it might be more effort to revert then add it back?

**Comment by neuromusic** [comment] 2022-07-26 16:37
why are we seeing these npe2 fields for `napari-deepfinder` (which is a real plugin but doesn't exist on the hub) and not for `foobar` (which isn't a real plugin)

**Comment by richaagarwal** [comment] 2022-07-26 19:13
@klai95 @potating-potato any idea why we wouldn't be seeing data from https://pypi.org/pypi/napari-deepfinder/json populated yet on the hub side?

**Comment by DragaDoncila** [comment] 2022-07-26 20:01
>  why are we seeing these npe2 fields for napari-deepfinder (which is a real plugin but doesn't exist on the hub) and not for foobar (which isn't a real plugin)

@neuromusic probably a quirk of when we're returning information. We decided early on that `npe2` metadata would always be "available" in the metadata dictionary, so we return default values when we can't retrieve "real" information. When a plugin doesn't exist at all we do an early return of `{}`.

**Comment by neuromusic** [comment] 2022-07-26 20:46
> When a plugin doesn't exist at all

@DragaDoncila so even though it's not showing up, `napari-deepfinder` must exist somewhere in the hub backend?

**Comment by DragaDoncila** [comment] 2022-07-26 20:49
@neuromusic correct - somewhere somehow, the napari hub backend is aware of `napari-deepfinder` and trying to process it, but not finding the PyPI metadata correctly.

**Comment by potating-potato** [comment] 2022-07-27 15:32
For some reason, the backend data for napari-deepfinder was corrupted, I deleted them and the repopulation of the data is then successful. The reason for the corruption is not yet known. I don't have any additional context but that the corrupted json contains nothing but "conda: []",  this is not expected from the typical indexing, I believe this is probably related to npe2 somehow

**Comment by richaagarwal** [comment] 2022-08-02 22:16
@klai95 will be doing some exploration on this to understand what may be causing these intermittent lags reported here as well as in #200.  In the meantime, if anyone notices this with any additional plugins, please let us knos!

**Comment by pr4deepr** [comment] 2022-08-02 23:48
Thanks for looking into this. 
Just as a follow up from the original post, napari-lattice plugin appears on napari-hub but doesn't update when a new release is available on pypi. 

[v 0.1.5 in pypi](https://pypi.org/project/napari-lattice/)

[still v 0.1.4b in napari-hub](https://www.napari-hub.org/plugins/napari-lattice)

**Comment by potating-potato** [comment] 2022-08-03 17:41
I digged around on the napari-lattice and I think I found the gap:
This may be related to https://github.com/chanzuckerberg/napari-hub/pull/605/files

when napari-lattice 0.1.5 published, we correctly fetched it and created a profile for it in our system, however when we populate the metadata, we used the non-versioned pypi API to get the latest, which seems to have not updated to correctly report the metadata for 0.1.5, as a result, the 0.1.5 profile is corrupted with 0.1.4b0 data when it was indexed. I will submit another PR to fix this

**Comment by tlambert03** [comment] 2022-08-03 17:44
hey @potating-potato, let me know if there's anything I can do to facilitate here with npe2api.  napari-lattice is looking good here: https://github.com/napari/npe2api/blob/main/public/manifest/napari-lattice.json

**Comment by potating-potato** [comment] 2022-08-03 17:59
> hey @potating-potato, let me know if there's anything I can do to facilitate here with npe2api. napari-lattice is looking good here: https://github.com/napari/npe2api/blob/main/public/manifest/napari-lattice.json

thanks for the help! I think I have found the issue and going to submit a PR to close this.

**Comment by richaagarwal** [comment] 2022-08-04 18:42
Just to give a quick update here:

I think we may have pinpointed the cause here.  Our hypothesis is that the lag may be due to PyPI's non-versioned endpoint sometimes taking time to catch up with the latest release data. For instance, https://pypi.org/pypi/mage-ai/json currently does not reflect latest release data available in https://pypi.org/pypi/mage-ai/0.2.1/json.  

#608 outlines a potential fix to this.

**Comment by richaagarwal** [comment] 2022-10-10 20:04
I am going to close this since we have #608 to track work on a potential fix.  We can re-open this in the future if needed or the situation worsens.

**Closed by richaagarwal** 2022-10-10 20:04 UTC
Labels: bug, P1
