### ISSUE TITLE
Google should not be crawling staging site

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#391] opened 2022-01-17 00:26 UTC
#### Description
Google should not be crawling `staging.napari-hub.org`

#### Steps/Code to Reproduce
Go to Google Search Console

#### Actual Results
![image](https://user-images.githubusercontent.com/1245615/149684253-1672ae9f-2e7b-4bba-a690-592197117e5e.png)

**Comment by codemonkey800** [comment] 2022-01-24 20:08
Hmm, we have the `noindex` tag enabled:

![image](https://user-images.githubusercontent.com/2176050/150856519-598db419-d39f-470d-8912-9931b19fac3b.png)

and I also confirmed that I'm not seeing it on Google Search results up to 3 pages for the query `napari hub staging`.  I'll look into it and see what's up

**Comment by codemonkey800** [comment] 2022-01-24 20:54
Ahh I think I got it. This might be fixed by https://github.com/chanzuckerberg/napari-hub/pull/405. I noticed in the screenshot that the issue is for the error pages. This is accidentally being included in the `sitemap.xml`, which conflicts with the `noindex` tag:

![image](https://user-images.githubusercontent.com/2176050/150863094-4defd09b-8d79-495a-b762-1ff1b81b2fc8.png)

**Comment by potating-potato** [comment] 2022-01-27 23:03
is there a way to confirm this is fixed and close the issue?

**Comment by codemonkey800** [comment] 2022-01-27 23:10
@potating-potato I'll need to re-run the web crawler in Google Search Console, but not sure how long that'll take since the queue for web crawling is a blackbox to us lol

**Comment by codemonkey800** [comment] 2022-01-31 18:39
First validation test passed:

![image](https://user-images.githubusercontent.com/2176050/151852847-05bba04e-ee89-4d8a-b7d6-f49bcdf6f9ba.png)

Still waiting on two more validation tests:

![image](https://user-images.githubusercontent.com/2176050/151852906-0ff45475-41f3-4399-9d3c-b299d85c9456.png)

**Closed** 2022-03-08 03:26 UTC
Labels: bug
