### ISSUE TITLE
pagination should follow browsers fwd/back controls

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#296] opened 2021-10-22 03:00 UTC
#### Description

When you click "back" when deep into pagination results, the browser goes back to the page prior to the search results page

#### Steps/Code to Reproduce

1. start on another page
2. navigate to napari-hub.org
3. click into pagination results
4. click "back"

#### Expected Results

I expected that hitting the "back" button would take me to the previous page of results

#### Actual Results

Back takes me out of the napari hub, to whatever page I was on for (1)

https://user-images.githubusercontent.com/1245615/138384880-9c1ef04e-89dd-44dc-ad76-eedd51772c84.mov

**Comment by neuromusic** [comment] 2022-08-15 22:49
note: before implementation, need to clarify expected behavior & state history when filtering, searching, and their interaction with pagination

**Comment by richaagarwal** [comment] 2023-08-17 08:02
This seems to be the behavior now! Going to close this out, but since we never got into the details of expected behavior, we can always reopen or track in a new issue in the future if needed.

**Closed by richaagarwal** 2023-08-17 08:02 UTC
Labels: enhancement, P1, good first issue, frontend
