### ISSUE TITLE
Cannot find the napari-hello plugin

### ISSUE THREAD

**Issue by GaGu818** [chanzuckerberg/napari-hub#401] opened 2022-01-24 09:14 UTC

**Comment by GaGu818** [comment] 2022-01-24 09:19
Hello,

I am trying to explore the napari plugin through the tutorial. I followed https://napari.org/plugins/stable/first_plugin.html to build a napari-hello example, but when I make it pip install -e . and napari, there is no this package shown. in Plugin -> install/uninstall plugin, and if I manually plug the local location to the install by url/file section, it still shows nothing. If I show the status, it would show this
  Stored in directory: /Users/yuexu/Library/Caches/pip/wheels/8e/c9/b7/353008671eb5dd037bd0e69553ab07f2a25b38e69894f53071
Successfully built napari-hello

Installing collected packages: napari-hello
  Attempting uninstall: napari-hello
    Found existing installation: napari-hello 0.0.1

    Can't uninstall 'napari-hello'. No files were found to uninstall.

Successfully installed napari-hello-0.0.1

But after I close it, no napari-hello section appears in the plugin list, and there is no button to run, nothing happens. I wonder that do you have any idea about why nothing appear after I install it? Did I install successfully?

**Comment by potating-potato** [comment] 2022-01-24 17:57
Hello, thanks for reaching out! I would like to politely point out that this is not a bug in neither napari nor napari-hub.

This behavior that you see is because of how packages are managed in python, when installed as `pip install -e .` napari cannot install nor uninstall this package via the name. Therefore you are seeing the error message. 

An alternative is to build the wheel and install from the wheel instead of `editable mode from the local file (pip install -e .)`, you can usually build the wheel with python setup tools `python setup.py sdist bdist_wheel` and then install the wheel from napari using the wheel location (after successful build it should be under your project/dist/****.whl), and then you would see this plugin showing up normally in the plugin menu

I will make sure to pass this feedback to our documentation working group and flag this confusing part in our documentation!

**Comment by tlambert03** [comment] 2022-01-25 22:06
Hi @GaGu818, I'm actually surprised to hear this.  You _should_ be able to see the package in the built-in plugin installer, and uninstall it there.  Can you confirm for me that you definitely had the text described in [this section of the docs](https://napari.org/plugins/stable/first_plugin.html#update-setup-cfg) in your setup.cfg, _before_ you ran `pip install -e .`?

```yaml
[metadata]
name = napari-hello
version = 0.0.1
classifiers =
    Framework :: napari

[options]
packages = find:
install_requires =
    napari

[options.package_data]
napari-hello = napari.yaml

[options.entry_points]
napari.manifest =
    napari-hello = napari_hello:napari.yaml
```

If not, napari won't find it.  You can always double check that text and rerun `pip install -e .` if you want

**Comment by neuromusic** [comment] 2022-01-26 16:12
Since this isn't a bug with the napari hub, I'm going to close this issue.

@GaGu818, if @tlambert03's suggestion doesn't solve your problem, can you start a thread on https://image.sc/tag/napari? That will be a better place for the whole napari community to help you debug your plugin. If it turns out that there is a bug with napari, https://github.com/napari/napari/issues is the best place to report such issues.

**Closed by neuromusic** 2022-01-26 16:12 UTC

**Comment by SilverViking** [comment] 2022-05-18 11:20
I accidentally ran into this same issue, so I thought I'd add the explanation here in case others bump into it as well.

What happened to me (and probably also to @GaGu818) is that I accidentally installed an older version of napari that does not support npe2 plugins yet. After starting napari the ``napari-hello`` plugin indeed is not found.

This situation can arise if one does not carefully follow the [installation instructions](https://napari.org/tutorials/fundamentals/installation.html#install-as-python-package-recommended). For example, this will result in a bad environment with an old napari:

```
conda create -n napari-env python=3.9   # WRONG -c conda-forge is also needed here
conda activate napari-env
conda install -c conda-forge napari
napari --version
# napari version 0.4.12     Oops, does not support npe2 plugins
```

If I follow the napari installation instructions more closely I get a more recent napari (0.4.14), and after installing the ``napari-hello`` plugin using ``pip install -e .`` it gets picked up by napari and works just fine. So, as mentioned by @tlambert03, the plugin *can* indeed be successfully installed with ``pip install -e .``
