### ISSUE TITLE
Subscribe button is not responsive

### ISSUE THREAD

**Issue by lmarcos** [chanzuckerberg/napari-hub#1284] opened 2023-10-03 23:12 UTC
#### Description
Subscribe button is not responsive

#### Steps/Code to Reproduce
1. Go to https://www.napari-hub.org/
2. Navigate to bottom of page
3. Enter correct email address in "Sign up to receive updates" section
4. Click on <Subscribe> button

#### Expected Results
Thanks for subscribing message should be displayed

#### Actual Results
Nothing happens

https://github.com/chanzuckerberg/napari-hub/assets/7291920/aa4cac65-7d97-401a-ab82-c58647f01959

**Comment by richaagarwal** [comment] 2023-10-04 19:59
@lauramarcos This worked for me when I tested it just now - perhaps it's an intermittent issue? Are you able to reproduce again?

**Comment by lmarcos** [comment] 2023-10-04 21:52
it is still not working for me and I already tried other browsers @richaagarwal

**Comment by richaagarwal** [comment] 2023-10-04 23:00
I've tried Safari & Chrome and they are both working for me. I also tried after navigating to different pages of search results. Which browsers have you tried @lmarcos?

@manasaV3 or @codemonkey800 could one of you see if you're able to reproduce?

**Comment by richaagarwal** [comment] 2023-10-04 23:02
Oh, I think it may be the e-mail address you are trying to use @lmarcos - have you always tested with @test.com ? It seems like we may be validating or filtering that out somehow. Using @test.com doesn't work for me either.  cc @codemonkey800

**Comment by richaagarwal** [comment] 2023-10-05 19:24
@codemonkey800 thanks for looking into it! I'm going to close this issue out because I think this is enough of an edge case and wouldn't block real users from subscribing. 

@lauramarcos it would still be helpful to know if you've always used this @test to test this, but going forward could you test with a real e-mail address? feel free to use one of ours :)

**Closed by richaagarwal** 2023-10-05 19:24 UTC
Labels: bug

**Comment by lmarcos** [comment] 2023-10-05 20:55
i used to text this feature with [laura@test.com](mailto:laura@test.com) and used to work, but I will test with normal domain going forward... thank you both @richaagarwal @codemonkey800
